namaMakanan_1 =	input("Masukkan Nama Makanan_1: ")
namaMakanan_2 = input("Masukkan Nama Makanan_2: ")
namaMinuman_3 = input("Masukkan Nama Minuman_3: ")	 
kodeMakanan_1 = int(input("Masukkan Kode KodeMakanan_1: "))
kodeMakanan_2 = int(input("Masukkan Kode KodeMakanan_2: "))	
kodeMinuman_3 = int(input("Masukkan Kode KodeMinuman_3: "))
hargaMakanan_1 = float(input("Masukkan Harga hargaMakanan_1: "))
hargaMakanan_2 = float(input("Masukkan Harga hargaMakanan_2: "))	
hargaMinuman_3 = float(input("Masukkan Harga hargaMakanan_3: "))
estimasiPembuatanMakanan_1 = int(input("Masukkan Estimasi estimasiPembuatanMakanan_1: "))	
estimasiPembuatanMakanan_2 = int(input("Masukkan Estimasi estimasiPembuatanMakanan_2: "))
estimasiPembuatanMinuman_3 = int(input("Masukkan Estimasi estimasiPembuatanMinuman_3: "))
diskonMakanan_1 = float(input("Masukkan Diskon diskonMakanan_1: "))
diskonMakanan_2 = float(input("Masukkan Diskon diskonMakanan_2: "))
diskonMinuman_3 = float(input("Masukkan Diskon diskonMinuman_3: "))
 
